spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-large
    vectorstore:
      azure:
        url: ${SEARCH_ENDPOINT}
        api-key: ${SEARCH_API_KEY}
        initialize-schema: true
  shell:
    interactive:
      enabled: true
    script:
      enabled: true
  main:
    web-application-type: NONE