spring:
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      embedding-api-key: ${SPRING_AI_OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-ada-002
      base-url: https://api.openai.com/
      chat:
        options:
          temperature: 0.2
          model: gpt-3.5-turbo
  main:
    web-application-type: NONE
azure:
  aisearch:
    api-key: ${AZURE_AI_SEARCH_API_KEY}
    url: ${AZURE_AI_SEARCH_ENDPOINT}